# Generated by Django 5.2.1 on 2025-05-20 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('herramientas', 'Herramientas'), ('materiales', 'Materiales de Construcción'), ('seguridad', 'Equipos de Seguridad'), ('tornillos', 'Tornillos y Anclajes'), ('adhesivos', 'Fijaciones y Adhesivos'), ('medicion', 'Equipos de Medición')], max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
            ],
        ),
    ]
