# Generated by Django 5.2.4 on 2025-07-04 03:33

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('herramientas', 'Herramientas'), ('materiales', 'Materiales de Construcción'), ('seguridad', 'Equipos de Seguridad'), ('tornillos', 'Tornillos y Anclajes'), ('adhesivos', 'Fijaciones y Adhesivos'), ('medicion', 'Equipos de Medición')], max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('calle', models.CharField(max_length=200)),
                ('numeracion', models.CharField(max_length=20)),
                ('comuna', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
            },
        ),
        migrations.CreateModel(
            name='PrecioProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=datetime.datetime.now)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Precio Producto',
                'verbose_name_plural': 'Precios Productos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='InventarioProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('ultima_actualizacion', models.DateTimeField(default=datetime.datetime.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='inventario.producto')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='inventario.sucursal')),
            ],
            options={
                'verbose_name': 'Inventario Producto',
                'verbose_name_plural': 'Inventarios Productos',
                'unique_together': {('producto', 'sucursal')},
            },
        ),
    ]
