# Generated by Django 5.2.1 on 2025-07-06 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrador',
            options={'verbose_name': 'Administrador Carrito', 'verbose_name_plural': 'Administradores Carrito'},
        ),
        migrations.AlterField(
            model_name='administrador',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carrito_administrador', to=settings.AUTH_USER_MODEL),
        ),
    ]
